#
# SPDX-License-Identifier: BSD-3-Clause
#
srcs_machine += [
  'pgmspace/memccpy_P.c',
  'pgmspace/memchr_P.c',
  'pgmspace/memcmp_P.c',
  'pgmspace/memcpy_P.c',
  'pgmspace/memmem_P.c',
  'pgmspace/printf_P.c',
  'pgmspace/snprintf_P.c',
  'pgmspace/sprintf_P.c',
  'pgmspace/strncasecmp_P.c',
  'pgmspace/strncat_P.c',
  'pgmspace/strncmp_P.c',
  'pgmspace/strncpy_P.c',
  'pgmspace/strnlen_P.c',
  'pgmspace/strnstr_P.c',
  'pgmspace/strstr_P.c',
  'pgmspace/vsnprintf_P.c',
]
